# Generated by Django 5.0.2 on 2024-03-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_delete_hawa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangesLogs',
        ),
    ]
