# Generated by Django 5.0.2 on 2024-03-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_otpcode_delete_otptable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
