# Generated by Django 5.0.2 on 2024-03-27 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
