# Generated by Django 5.0.2 on 2024-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuUsage', models.FloatField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ramUsage', models.FloatField(max_length=20)),
                ('criticality', models.BooleanField(default=False)),
            ],
        ),
    ]
